spring:
  application:
    name: ImoocMerchants
  datasource:
    url: spring.datasource.url=jdbc:mysql:?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
    username: 
    password: 

  kafka:
    bootstrap-servers: 
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

  data:
      hbase:
        quorum: 
        rootDir: 
        nodeParent: /hbase

  redis:
    host: 
    port: 

server:
  port: 9528

logging:
  level: debug:true
  file: imooc-passbook.log
